# .pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# black linter
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
    args:
        # these folders wont be formatted by black
        - --exclude="""\.git |
          \.__pycache__|
          \.venv"""

# flake8 linter
#-   repo: 8ddhttps://github.com/pycqa/flake8
#    rev: 4.0.1  # pick a git hash / tag to point to
#    hooks:
#    -   id: flake8

#     args: # arguments to configure flake8
#        # making flake8 line length compatible with black
#        - "--max-line-length=88"
#        - "--max-complexity=18"
#        - "--select=B,C,E,F,W,T4,B9"

        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
#        - "--ignore=E203,E266,E501,W503,F403,F401,E402"


# sort imports
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
